version: '3.8'

services:
  postgres:
    image: postgres:15
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: invoices
      PGDATA: /data/postgres
    volumes:
      - ./.docker/postgres:/data/postgres
    networks:
      - invoices-network

  redis:
    image: redis:7.2
    restart: unless-stopped
    ports:
      - 6379:6379
    volumes:
      - ./.docker/redis:/data
    networks:
      - invoices-network

networks:
  invoices-network:
    driver: bridge
